repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--check-only]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--skip=ultrasound/third_party/*", "--write-changes"]
        additional_dependencies:
        - tomli
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
    - id: clang-format
      types_or: [c++, c, cuda]
      exclude: '^ultrasound/third_party/*'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      exclude: '^ultrasound/third_party/'
    - id: end-of-file-fixer
      exclude: '^ultrasound/third_party/'
    - id: check-yaml
    - id: check-added-large-files
