repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6  # Use the latest version of clang-format available
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
    files: '\.(cpp|hpp|c|h|cu|cuh)$'
    exclude: '^third_party/'

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: '^third_party/'
  - id: end-of-file-fixer
    exclude: '^third_party/'
  - id: check-yaml
  - id: check-added-large-files
